theme: jekyll-theme-cayman
title: Benjamin L'Huillier
description: Cosmologist & Astrophysicist, Assistant Professor at Sejong University, Seoul, Korea
url: "https://blhuillier.github.io"
# Links for navigation
header_pages:
  - index.md
  - research.md
  - teaching.md
  - background.md
  - mygroup.md
