name: Deploy Gatsby Site to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build the Gatsby site
        run: npm run build --prefix-paths

      - name: Configure Git user
        run: |
          git config --global user.email "lhuillier.benjamin@gmail.com"
          git config --global user.name "Benjamin L'Huillier"

      # Ensure CNAME file is copied to the public directory for deployment
      - name: Prepare CNAME file for GitHub Pages
        run: cp CNAME public/CNAME

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages -d public -b gh-pages -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
